### ISSUE TITLE
Investigate: do download links expire after a period of time?

### ISSUE THREAD

**Issue by Wiscmapper** [WIStCart/geodata-processing#21]
After a link is generated, does it persist forever?  How long can that link be used?  You can test this with a combination of trial and error, and digging through the API docs.

**Comment by JSeibel55** [comment]
Tested a download link generated on 8/31 and it is still working 2 months later. Abby and I have yet to find indication in the API documentation that links expire.

**Comment by JSeibel55** [comment]
Tested today a download link generated on 8/31. Looks like the download may have expired as the browser returns "The requested failed. Invalid Download". Sometime before 8 months the download link expires.

The browse path is still working from the link generated on 8/31.
