### ISSUE TITLE
NEW Script to read geojson and reduce the coordinate precision to a specified decimal place

### ISSUE THREAD

**Issue by Wiscmapper** [WIStCart/geodata-processing#26]
Read input file(s) from a folder, output new file(s) at specified output location

constants: decimal precision, output file folder

**Comment by HaydenElza** [comment]
Addressed in commit 7672469c5f58b3f096958de1c5040a176975e1bf.

**Comment by Wiscmapper** [comment]
Actually, this was a placeholder for the future; it would be great to have a script that can read existing geojsons to reduce the precision.

**Comment by HaydenElza** [comment]
Ah, understood.

**Comment by HaydenElza** [comment]
Note for later: This [code block](https://github.com/WIStCart/geodata-processing/blob/7672469c5f58b3f096958de1c5040a176975e1bf/migrate%20from%20lidar%20tile%20viewer/migrate.py#L45-L51) from commit https://github.com/WIStCart/geodata-processing/commit/7672469c5f58b3f096958de1c5040a176975e1bf can be adapted into a stand alone script to reduce coordinate precision.
